server.port: 0

spring.application.name: DemoApplication

spring.jmx.enabled: false

spring.cloud.stream:
    bindings:
        input:
            destination: "foos"
            consumer.headerMode: "raw"
        output:
            destination: "counts-id"
            producer.headerMode: "raw"
    kafka.streams.binder:
        brokers: "localhost:9092"
        zkNodes: "localhost:2181"
        configuration:
            commit.interval.ms: 1000
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    kafka.streams.bindings:
        output:
            producer.keySerde: org.apache.kafka.common.serialization.Serdes$IntegerSerde